# Generated by Django 5.2.8 on 2025-11-30 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_fornecedor_postagem_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.pessoa'),
            preserve_default=False,
        ),
    ]
