# Generated by Django 5.2.8 on 2025-11-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_pessoa_alter_fornecedor_options_fornecedor_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='pessoa',
        ),
    ]
