# Generated by Django 5.2.8 on 2025-11-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_fornecedor_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(default=12345678910, max_length=11),
            preserve_default=False,
        ),
    ]
