# Generated by Django 5.2.8 on 2025-11-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feed.pessoa'),
            preserve_default=False,
        ),
    ]
