# Generated by Django 5.2.8 on 2025-12-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_fornecedor_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='date',
        ),
    ]
